version: '3'

volumes:
  database:
  www:
  traefik:

networks:
  frontend:
  net_db:

services: 
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    env_file: .env
    networks:
      - net_db
    volumes:
      - database:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on: 
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${HOST}.${DOMINIO}`) || (Host(`${DOMINIO}`))"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    env_file: .env
    networks: 
      - frontend
      - net_db
    volumes:
      - www:/var/www/html

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    restart: always
    depends_on: 
      - wordpress
    command:
     #- "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=${EMAIL}""
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
      - "--providers.docker.network=frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik:/letsencrypt
    networks: 
      - frontend
