- name: Criando Diretorio para deploy
  become: yes
  file:
    path: '{{ work_dir }}'
    state: directory
    mode: '2775'
    owner: root
    group: docker
  register: create_directory

- name: Copiando files para deploy
  copy: src={{ item }} dest={{ work_dir }}
  with_items:
    - .env
    - docker-compose.yaml
    - README.md
  register: copy_files

- name: Subindo o servico com o docker-compose
  shell: docker-compose --project-directory {{ work_dir }} up -d
  register: service_up