- name: Criando Diretorio para deploy
  file:
    path: {{ work_dir }}
    state: directory
    mode: '2755'
    owner: root
    group: docker
  register: create_directory

- name: Copiando files para deploy
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - .env
    - docker-compose.yaml
    - README.md
  register: copy_files

- name: Subindo o servico com o docker-compose
  shell: docker-compose --project-directory {{ work_dir }} up -d
  register: service_up